// Canonical list of genres v5/v6 pipelines are allowed to reference.
// Consumed by the event-playlist Haiku prompt (api/v6/account/event-playlist.js).
//
// ⚠️ FOUR PLACES enumerate the genre universe today. The musical-directions
// R1 prompt is the SOURCE OF TRUTH; any change must be applied to all four
// or downstream lookups will silently drop the affected genre:
//   1. v6/generation/musical-directions.js → GENRE_UNIVERSE_SECTION  (source of truth; R1 + R2 prompts)
//   2. v5/generation/musical-directions.js → GENRE_UNIVERSE_SECTION  (byte-identical mirror; Ami's dashboard reads it)
//   3. v6/generation/genre-list.js         → this file               (event-playlist Haiku prompt)
//   4. v6/generation/direction-edit-chat-prompt.js → ## Genre universe block (profile-tab direction-edit chat)
// DB matches are case-insensitive but spelling must match verbatim.
//
// Order here is roughly thematic (rock → funk → jazz → classical/world →
// mediterranean → latin → caribbean → lofi/hiphop → r&b → pop clusters) and
// does NOT need to match the prompt's alphabetical order — it just needs to
// contain the same set of strings. Last synced against the prompt: 2026-09-02.

export const GENRES = [
  'Heavy Rock+Metal',
  'Nu Metal',
  'Grunge',
  'Rock',
  'Indie Rock',
  'IndieTronica',
  'Post Punk',
  'Punk',
  'Indie Folk',
  'Folk',
  'Japanese Folk',
  'Country',
  'Blues',
  'Jazz (Standards)',
  'French Jazz',
  'Gypsy jazz',
  'Smooth Jazz',
  'Late Night jazz',
  'Swing Jazz',
  'Easy Listening',
  'French Ye Ye',
  'Funk',
  'Afro Funk',
  'French Funk',
  'Italian Funk',
  'Greek Funk',
  'Ethio-Jazz',
  'Neo Exotica',
  'Chamber music',
  'Piano Impressionism',
  'Baroque',
  'Medieval Music',
  'African Highlife',
  'Arabic Funk',
  'Tishoumaren',
  'Dabke',
  'Algerian Rai',
  'Arab Classic',
  'Laiko',
  'Rebetiko',
  'Turk Arabesk',
  'Anatolian Psychedelic Rock',
  'Flamenco',
  'Fado',
  'Bossa Nova',
  'Samba',
  'Samba-Choro',
  'Salsa',
  'Cha Cha Cha',
  'Bolero',
  'Argentine Tango',
  'Peruvian Cumbia',
  'Peruvian Chicha',
  'Latin Boogaloo',
  'Latin Funk',
  'Dancehall',
  'Reggaeton',
  'Reggae',
  'Lovers Rock',
  'LoFi Bossa',
  'LoFi Beats',
  'Desi LoFi',
  'JazzHop',
  'Acid Jazz',
  'Neo Soul',
  'Rnb',
  'French RnB',
  'Japanese RnB',
  'Korean RnB',
  'Hip Hop',
  'French Hip Hop',
  'German Hip Hop',
  'Icelandic Hip Hop',
  'Trap',
  'Grime & Drill',
  'Thai Molam',
  'Japanese City Pop',
  'Chinese City Pop',
  'Disco',
  'Nu Disco',
  'Italo Disco',
  'Indie Dance',
  'AfroBeats',
  'Afro House',
  'Amapiano',
  'French DownTempo',
  'DownTempo',
  'Organic House',
  'Deep House',
  'Soulful House',
  'Electro Swing',
  'Jazz House',
  'Tech House',
  'UKG',
  'Dubstep',
  'Uplifting & Vocal Trance',
  'Progressive & Psy Trance',
  'Modern Pop',
  'Alternative pop',
  'Bedroom Pop',
  'Female Pop',
  'Britpop',
  'Electro Pop',
  'K-Pop',
  'Cantopop',
  '80s Pop',
  '90\'s pop party',
  'פופ מזרחית',
  'מזרחית ישנה',
  'רוק ישראלי',
  'בלדות ישראליות',
  'שירי ארץ ישראל',
  'שירי יום הזיכרון והשואה',
];

export const GENRE_SET = new Set(GENRES);
