// Canonical list of genres v5/v6 pipelines are allowed to reference.
// Kept in sync with the identical comma-list embedded in
// v6/generation/musical-directions.js → EDITABLE_PROMPT_SECTION.
//
// The main onboarding flow's prompt is a large static string that gets
// prompt-cached by Anthropic; we deliberately do NOT interpolate this array
// into that string yet (would invalidate the cache prefix). This module is
// the source of truth for other callers — currently the event-playlist
// endpoint under /api/v6/account/.
//
// If you edit either list, edit both. TODO(future): switch musical-directions
// to interpolate from here once we're ready to re-cache the prompt.
//
// Order matches Data Box Tab 2 sheet order (last synced 2026-08-XX). Keep it
// that way — the sheet is authoritative and this file mirrors it exactly so
// future diffs against the sheet are trivial.

export const GENRES = [
  'Heavy Rock+Metal',
  'Nu Metal',
  'Grunge',
  'Rock',
  'Indie Rock',
  'IndieTronica',
  'Post Punk',
  'Punk',
  'Indie Folk',
  'Folk',
  'Country',
  'Blues',
  'Jazz (Standards)',
  'French Jazz',
  'Gypsy jazz',
  'Smooth Jazz',
  'Late Night jazz',
  'Swing Jazz',
  'Easy Listening',
  'French Ye Ye',
  'Funk',
  'World Funk',
  'Afro Funk',
  'Ethio-Jazz',
  'Neo Exotica',
  'Chamber music',
  'Piano Impressionism',
  'Baroque',
  'Medieval Music',
  'African Highlife',
  'Arabic Funk',
  'Tishoumaren',
  'Dabke',
  'Algerian Rai',
  'Arab Classic',
  'Laiko',
  'Rebetiko',
  'Turk Arabesk',
  'Anatolian Psychedelic Rock',
  'Flamenco',
  'Fado',
  'Bossa Nova',
  'Samba',
  'Salsa',
  'Cha Cha Cha',
  'Bolero',
  'Argentine Tango',
  'Peruvian Cumbia',
  'Dancehall',
  'Reggaeton',
  'Reggae',
  'Lovers Rock',
  'LoFi Bossa',
  'LoFi Beats',
  'Acid Jazz',
  'Neo Soul',
  'Rnb',
  'French RnB',
  'Japanese RnB',
  'Korean RnB',
  'Hip Hop',
  'French Hip Hop',
  'Icelandic Hip Hop',
  'Trap',
  'Grime & Drill',
  'Thai Molam Funk',
  'Japanese City Pop',
  'Disco',
  'Nu Disco',
  'Italo Disco',
  'Indie Dance',
  'AfroBeats',
  'Afro House',
  'Amapiano',
  'French DownTempo',
  'DownTempo',
  'Organic House',
  'Deep House',
  'Soulful House',
  'Electro Swing',
  'Jazz House',
  'Tech House',
  'UKG',
  'Dubstep',
  'Uplifting & Vocal Trance',
  'Progressive & Psy Trance',
  'Modern Pop',
  'Alternative pop',
  'Electro Pop',
  'K-Pop',
  '80s Pop',
  '90\'s pop party',
  'פופ מזרחית',
  'מזרחית ישנה',
  'רוק ישראלי',
  'שירי ארץ ישראל',
];

export const GENRE_SET = new Set(GENRES);
